version: '2.3'
services:
  transfer_train-container:
    container_name: "train-container"
    build:
      context: .
      dockerfile: Dockerfile_train
    volumes:
      - ./data:/home/prgrmcode/app/data
      - model-volume:/home/prgrmcode/app/model
    # command: ["python3", "transfer_learning_pytorch.py"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

  transfer_app-container:
    container_name: app-container
    depends_on:
      - transfer_train-container
    build:
      context: .
      dockerfile: Dockerfile_app
    volumes:
      - ./data:/home/prgrmcode/app/data
      - model-volume:/home/prgrmcode/app/model
    # command: ["python3", "app_script.py"]
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    
volumes:
  model-volume:

